version: '3.8'

services:
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  nodeapp:
    image: node:20
    volumes:
      - ./dist:/usr/src/app
    working_dir: /usr/src/app
    command: node main.js
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis
    ports:
      - "3000:3000"

volumes:
  redis-data:
